services:
  app:
    build: .
    image: backend3-entregable:latest
    container_name: backend3-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - MONGODB_URI=mongodb://mongo:27017/backend-3-entregable
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo:
    image: mongo:7
    container_name: backend3-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=back3

volumes:
  mongo_data: